### ISSUE TITLE
Detailed explanation of using matrix-react-sdk

### ISSUE THREAD

**Issue by iromjkee** [matrix-org/matrix-react-sdk#10562]
Hello, I've tried to setup matrix-react-sdk in order to use matrix chat and its UI components and etc in my app. But I can't find any valid examples and all the time just get that matrix-react-sdk is not resolved by webpack, can you please help me or just give the link to the valid documentation of how to start it from scratch or something?

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk#matrix-react-sdk

> As of Aug 2018, the only skin that exists is [vector-im/element-web](https://github.com/vector-im/element-web/); it and matrix-org/matrix-react-sdk should effectively be considered as a single project (for instance, matrix-react-sdk bugs are currently filed against vector-im/element-web rather than this project).
