### ISSUE TITLE
Unable to run matrix-element web react app on the local development environment

### ISSUE THREAD

**Issue by prncdev** [matrix-org/matrix-react-sdk#11051]
I am having an issue to run the element react font-end app on my local environment when I try to run this command is the `matrix-react-sdk`  with yarn like `yarn start` It will start building the app instead of opening on localhost, I don't want to run the entire app I just want to run only front-end app, React-app only, can you tell me how can I archive this?

**Comment by prncdev** [comment]
Bc itna chutiya project maine kabhi nhi dekha jisme documentation proper way mei liye huye nhi hai plus help suppot wale bhi itne gadhe hain ki kuchh sahi se btate bhi nhi hai sala view wala structure folder mei hai aur jaha structure wala code hona chahiye waha view wala code hai worst open source project seen ever!

**Comment by t3chguy** [comment]
Please open issue in vector-im/element-web as per https://github.com/matrix-org/matrix-react-sdk/issues/9666 along with full repro steps not just a thin overview. Exactly what steps you did, exactly what you are seeing. `yarn start` doesn't open your browser for you, you have to do that bit yourself as the console output says, open `http://localhost:8080` once `yarn start` is ready.
