### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Kurioni** [matrix-org/matrix-react-sdk#11578]
Hi all. Is there any normal documentation for this project, API description?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk#matrix-react-sdk

> As of Aug 2018, the only skin that exists is [vector-im/element-web](https://github.com/vector-im/element-web/); it and matrix-org/matrix-react-sdk should effectively be considered as a single project (for instance, matrix-react-sdk bugs are currently filed against vector-im/element-web rather than this project).

**Comment by Kurioni** [comment]
Please make proper documentation in the future. Digging into the vector.im project, you can not understand anything.

**Comment by t3chguy** [comment]
As per the top of the readme I linked, this SDK isn't usable by anything other than Element Web anymore.

**Comment by Kurioni** [comment]
It turns out that in your own projects you can only use **matrix-js-sdk**?

**Comment by t3chguy** [comment]
No, there are many other SDKs you can use. Matrix React SDK however is only usable if you want something that is basically Element Web, given it isn't a very clear SDK.
