### ISSUE TITLE
request: support text input with clipboard events disabled.

### ISSUE THREAD

**Issue by gcb** [matrix-org/matrix-react-sdk#11728]
some certification bodies requires disabling clipboardEvents. I will update this later on with any doc i can share.

This can impact govt and financial institution adoption of element-web (and other clients using this SDK) as it breaks pasting to the div-as-input component here.

Not to mention usability/18n as several niche browsers/extensions/ime input do not work well with that pattern.

you can simulate cases where that feature is not available on firefox, about:config, `dom.event.clipboardevents.enabled=false`. copy and cut (with preventDefault at the end of the methods) works fine. Only paste is impacted currently.

**Comment by gcb** [comment]
I can try a patch around https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/BasicMessageComposer.tsx#L357 but I am unsure about the second edge case (line 360). Someone more familiar with that would be more productive.

**Comment by gcb** [comment]
This sdk is not used anywhere else?

if it's only there, i guess they prefer rich-text over all integrations that are possible using a simple text box https://github.com/vector-im/element-web/issues/25544

thank you.

**Comment by t3chguy** [comment]
I guess you didn't read the README 

> As of Aug 2018, the only skin that exists is [vector-im/element-web](https://github.com/vector-im/element-web/); it and matrix-org/matrix-react-sdk should effectively be considered as a single project (for instance, matrix-react-sdk bugs are currently filed against vector-im/element-web rather than this project).
