### ISSUE TITLE
Cannot find type definition file for 'testing-library__jest-dom'.

### ISSUE THREAD

**Issue by MarcWadai** [matrix-org/matrix-react-sdk#12454]
## Description
I have a [fork](https://github.com/tchapgouv/matrix-react-sdk-tchap) of matrix-react-sdk that I use as a subtree in my project.
When trying to build my fork, it fails when running the command : 
`yarn build:types`

output : 
```
error TS2688: Cannot find type definition file for 'testing-library__jest-dom'.
  The file is in the program because:
    Entry point for implicit type library 'testing-library__jest-dom'


Found 1 error.
```

I didn't touch any configuration files or added any dependencies in the project.

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk/issues/9666
