### ISSUE TITLE
Avatar issue on 1:1 call

### ISSUE THREAD

**Issue by I-lander** [matrix-org/matrix-react-sdk#12488]
In a 1:1 private conversation with another person, when receiving a call, the avatar icon is stretch :

As it is: 
![2024-05-02_17-00](https://github.com/matrix-org/matrix-react-sdk/assets/91682618/9081492b-b652-4973-8622-608649cb9a3d)

As it should be:
![2024-05-02_17-00_1](https://github.com/matrix-org/matrix-react-sdk/assets/91682618/15ee57c9-73f2-4851-a77c-c6afadfa31ef)

The issue is due to the flex box of the parent element > mx_IncomingLegacyCallToast

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk/issues/9666
