### ISSUE TITLE
Stuck during package installation.

### ISSUE THREAD

**Issue by cnspary** [matrix-org/matrix-react-sdk#12508]
**Install Env:**
```
node version: v21.4.0
npm version: v10.2.4
npm i matrix-react-sdk@2.3.1
```

**Problem:**

when I install [package]@[version] by command `npm install npm i matrix-react-sdk@2.3.1`, the **installation process gets stuck and never ends**. CPU usage will rise to 100%. Memory usage will also rise and will never be freed.

Can someone helps check this out?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/issues/9666
