### ISSUE TITLE
Conference Call Continues to Ring When All Participants Deny Microphone Access

### ISSUE THREAD

**Issue by lea-aglz** [matrix-org/matrix-react-sdk#12517]
Hello, 
I've identified an issue, 
When I starting a conference, if all participants deny access to their microphones, the conference continues to ring indefinitely until someone grants microphone access.

Thank you, 

Regards, 
Léa Angelloz

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/issues/9666
