### ISSUE TITLE
Encryption forced off but users get prompt to setup keys

### ISSUE THREAD

**Issue by theslash** [matrix-org/matrix-react-sdk#12781]
Crossposting this here in hope that someone sees this and has a clue:

https://github.com/element-hq/element-web/issues/27711

Situation:
Encyption is set to off in element web (this worked for nearly a year), but users suddenly get prompts to setup encrpytion keys.

Verified on a test installation with newest synapse server + newest element.

my well-known:

```
location /.well-known/matrix/client {
  return 200 '{"m.homeserver": 
                {"base_url": "https://******.de"}, 
                "io.element.e2ee": 
                    {
                        "default": false, 
                        "force_disable": true, 
                        "secure_backup_required": false}
                    }';
  add_header Content-Type application/json;
  add_header "Access-Control-Allow-Origin" *;
}
```

Its a bit of a pressing issue, because now all users get the prompt to setup keys, and get nagged after every login.

Imho according to this:

https://github.com/matrix-org/matrix-react-sdk/pull/11125

this should not happen and didnt happen until now.

Thank you for your help

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk/issues/9666
