### ISSUE TITLE
Enable desktop notifications - TypeError

### ISSUE THREAD

**Issue by unhappymealqq** [matrix-org/matrix-react-sdk#602]
Hi guys, got a bug for you in /src/Notifier.js that actually comes from the electron Riot-web client:  the desktop notifications initially work until it's checked OFF.  Then it can't be re-enabled and throws the error:

Notifier.js:132 Uncaught TypeError: Cannot read property 'done' of undefined

Afterwards if you check this option, it will uncheck again whenever one of the radio buttons is selected and the page gets updated.

**Comment by richvdh** [comment]
Is this still an issue? If so please could you raise it at https://github.com/vector-im/riot-web/issues
